name: LED Test

# 触发条件：推送到 main 分支、PR 到 main 分支时执行
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-led:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      # 步骤 1：拉取代码到 GitHub 服务器
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2：安装 Python 依赖（Klipper 测试依赖 Python 3.7+）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # 兼容 Klipper 测试的版本

      # 步骤 3：安装 Klipper 测试所需的 Python 库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/_klipper3d/mkdocs-requirements.txt
          pip install -r scripts/klippy-requirements.txt  # Klipper 根目录下的依赖文件
          # 额外依赖（如 pytest 可选，Klipper 测试脚本本身可独立运行）

      # 步骤 4：执行 led.test 测试脚本
      - name: Run LED integration test
        run: |
          # 使用 Klipper 自带的测试脚本执行 led.test
          ./scripts/test-klippy.py test/klipper/led.test
