name: LED Test

# 触发条件：推送到 main 分支、PR 到 main 分支时执行
on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ main, master ]

jobs:
  test-led:
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      # 步骤 1：拉取代码到 GitHub 服务器
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤 2：安装 Python 依赖（Klipper 测试依赖 Python 3.7+）
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # 兼容 Klipper 测试的版本
    
      # 添加安装AVR工具链的步骤
      - name: Install AVR toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-avr avr-libc

      # 步骤 3：安装 Klipper 测试所需的 Python 库
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
          # Klipper 根目录下的依赖文件 
          # pip install -r docs/_klipper3d/mkdocs-requirements.txt --break-system-packages
          pip install -r scripts/klippy-requirements.txt --break-system-packages

      - name: Build firmware
        run: |
          make clean
          make

      # 步骤 4：执行 led.test 测试脚本
      - name: Run LED integration test
        run: |
          echo "******* Running LED integration test... *******"
          # 使用 Klipper 自带的测试脚本执行 led.test
          source venv/bin/activate
          python3 scripts/test_klippy.py -d out test/klippy/led.test